name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  build:
    runs-on: windows-latest  # Windows-машина

    steps:
      - uses: actions/checkout@v4  # Клонирует код

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build EXE
        run: pyinstaller --onefile --windowed --name InvoiceGenerator main.py

      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: InvoiceGenerator-Windows
          path: dist/InvoiceGenerator.exe
