name: Build Windows 7 Compatible EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8.10"
          architecture: "x86"

      - name: Install Windows 7 dependencies
        run: |
          choco install -y vcredist2010 kb2999226

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip==20.3.4
          pip install docxtpl==0.6.3 python-docx==0.8.7 pyinstaller==4.10

      - name: Build EXE
        run: |
          pyinstaller `
            --onefile `
            --noconfirm `
            --win-private-assemblies `
            --add-data "template.docx;." `
            --add-data "company_data.json;." `
            --target-architecture win32 `
            --runtime-tmpdir=. `
            --name InvoiceGenerator `
            --clean `
            main.py

      - name: Add VC++ Redist DLLs
        run: |
          copy "C:\Windows\System32\vcruntime140.dll" dist\
          copy "C:\Windows\System32\msvcp140.dll" dist\

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: InvoiceGenerator-Win7
          path: |
            dist/InvoiceGenerator.exe
            template.docx
            company_data.json
          retention-days: 5

      - name: Create portable package
        run: |
          Compress-Archive -Path .\dist\* -DestinationPath .\InvoiceGenerator-Win7-Portable.zip
          
      - name: Upload portable package
        uses: actions/upload-artifact@v4
        with:
          name: InvoiceGenerator-Win7-Portable
          path: InvoiceGenerator-Win7-Portable.zip
          retention-days: 5
