name: Build for Windows 7

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019  # Последняя версия с частичной поддержкой Win7

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Последняя поддерживаемая версия для Win7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Windows SDK
      run: |
        choco install -y windows-sdk-8.1

    - name: Build EXE
      run: |
        pyinstaller --onefile ^
          --win-private-assemblies ^
          --add-data "template.docx;." ^
          --runtime-tmpdir=. ^
          --name InvoiceGenerator ^
          main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: InvoiceGenerator-Win7
        path: dist/InvoiceGenerator.exe
